### ISSUE TITLE
fontconfig cannot be downloaded from bintray

### ISSUE THREAD

**Issue by ianfiske** [staticfloat/homebrew-juliadeps#57]
I am running Julia 0.3 on OS X Yosemite and am getting errors when trying to install the Cairo package.  It looks like the fontconfig bottle is missing.  When I do `Pkg.build('Cairo')` I get

```
INFO: Building Homebrew
From https://github.com/Homebrew/homebrew
   60722b2..b17e213  master     -> origin/master
HEAD is now at b17e213 doc: add xcode 6.4
HEAD is now at 5c6fc7f Merge branch 'staging'
INFO: Building Cairo
==> Installing cairo from staticfloat/homebrew-juliadeps
==> Installing dependencies for staticfloat/juliadeps/cairo: staticfloat/juliadeps/fontconfig, staticfloat/juliadeps/pixman
==> Installing staticfloat/juliadeps/cairo dependency: staticfloat/juliadeps/fontconfig
==> Downloading https://homebrew.bintray.com/bottles-staticfloat/homebrew-juliadeps/fontconfig-2.11.1.yosemite.bottle.3.tar.gz
Error: Failed to download resource "fontconfig"
Download failed: https://homebrew.bintray.com/bottles-staticfloat/homebrew-juliadeps/fontconfig-2.11.1.yosemite.bottle.3.tar.gz
Warning: Bottle installation failed: building from source.
Error: /Users/ianfiske/.julia/v0.3/Homebrew/deps/usr/opt/pkg-config not present or broken
Please reinstall staticfloat/juliadeps/pkg-config. Sorry :(
================================[ ERROR: Cairo ]================================

failed process: Process(`/Users/ianfiske/.julia/v0.3/Homebrew/deps/usr/bin/brew install --force-bottle staticfloat/juliadeps/cairo`, ProcessExited(1)) [1]
while loading /Users/ianfiske/.julia/v0.3/Cairo/deps/build.jl, in expression starting on line 144
```
Are the staticfloat bottles missing from bintray's homebrew repo?

**Comment by staticfloat** [comment]
Self-assigning so I know to take a look at this later

**Comment by staticfloat** [comment]
Can you please `Homebrew.update()` and try again.  I have pushed a fix that should mirror the bottles on our server so that this doesn't happen.

**Comment by ianfiske** [comment]
@staticfloat Thank you for the quick response!  Unfortunately, I still get a very similar error

```
INFO: Building Homebrew
HEAD is now at 975ee29 ant: remove bottle.
HEAD is now at 34e9769 Mirror bottles for fontconfig, freetype, pango and pixman to close #57
INFO: Building Cairo
==> Installing cairo from staticfloat/homebrew-juliadeps
==> Installing dependencies for staticfloat/juliadeps/cairo: staticfloat/juliadeps/fontconfig, staticfloat/juliadeps/pixman
==> Installing staticfloat/juliadeps/cairo dependency: staticfloat/juliadeps/fontconfig
==> Downloading https://juliabottles.s3.amazonaws.com/fontconfig-2.11.1.yosemite.bottle.3.tar.gz
Error: Failed to download resource "fontconfig"
Download failed: https://juliabottles.s3.amazonaws.com/fontconfig-2.11.1.yosemite.bottle.3.tar.gz
Warning: Bottle installation failed: building from source.
```

When I try to access the bottle in my browser at https://juliabottles.s3.amazonaws.com/fontconfig-2.11.1.yosemite.bottle.3.tar.gz, I get:
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
      <Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>00D279B447E400B7</RequestId><HostId>JShMD8m9RQCefMTkwjBn5ewdTyU8Ii/n4PdSARCEQCctSBJtQ+zigcQ3ROLCvmkb</HostId></Error>
```
It looks like an AWS permissions problem.

**Comment by staticfloat** [comment]
Aaaahhh, shoot.  I forgot to open up the permissions to Everyone.  Try again now?

**Comment by ianfiske** [comment]
Thank you!  That fixed the issue for me and Cairo.jl builds without errors.
